name: fruit_classifier # name of conda environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - openpyxl=3.0.9
  - pandas=1.4.2
  - numpy=1.22.3
  - scipy=1.8.0
  - scikit-learn=1.0.2
  - pillow=9.1.0
  - opencv=4.5.5
  - scikit-image=0.19.2
  - pip:
    - ipywidgets==7.7.0
    - black==22.3.0
    
  